SELECT RH.HISTORY_ID
     , RH.CAR_ID
     , TO_CHAR(RH.START_DATE, 'YYYY-MM-DD') AS START_DATE
     , TO_CHAR(RH.END_DATE, 'YYYY-MM-DD') AS END_DATE
     , CASE
           WHEN RH.END_DATE - RH.START_DATE >= 29 THEN '장기 대여'
           ELSE '단기 대여'
       END AS RENT_TYPE
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
 WHERE RH.START_DATE >= TO_DATE('2022-09-01', 'YYYY-MM-DD')
   AND RH.START_DATE < TO_DATE('2022-10-01', 'YYYY-MM-DD')
 ORDER BY RH.HISTORY_ID DESC;