SELECT   f.MEMBER_ID
       , f.MEMBER_NAME
       , f.GENDER
       , DATE_FORMAT(f.DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
  FROM MEMBER_PROFILE f
 WHERE MONTH(f.DATE_OF_BIRTH) = 3
       AND f.GENDER = 'W'
       AND f.TLNO IS NOT NULL
 ORDER BY f.MEMBER_ID;