SELECT B.BOOK_ID
     , TO_CHAR(B.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
  FROM BOOK B
 WHERE B.CATEGORY = '인문'
   AND B.PUBLISHED_DATE >= TO_DATE('2021-01-01', 'YYYY-MM-DD')
   AND B.PUBLISHED_DATE < TO_DATE('2022-01-01', 'YYYY-MM-DD')
 ORDER BY B.PUBLISHED_DATE;