SELECT GB.TITLE
     , GB.BOARD_ID
     , GR.REPLY_ID
     , GR.WRITER_ID
     , GR.CONTENTS
     , TO_CHAR(GR.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
  FROM USED_GOODS_BOARD GB
 INNER JOIN USED_GOODS_REPLY GR
    ON GR.BOARD_ID = GB.BOARD_ID
 WHERE GB.CREATED_DATE >= TO_DATE('2022-10-01', 'YYYY-MM-DD')
   AND GB.CREATED_DATE < TO_DATE('2022-11-01', 'YYYY-MM-DD')
 ORDER BY GR.CREATED_DATE, GB.TITLE;